### ISSUE TITLE
Request怎么拿到http的返回数据

### ISSUE THREAD

**Issue by niaonile** [LANIF-UI/cmn-utils#2]
Request怎么拿到http的返回数据，afterResponse拿到的是接口返回的

**Comment by weiq** [comment]
这样嘛？

```js
$$.get("http://httpbin.org/get", null, {
    responseType: null,    // 关键
    afterResponse: null
}).then(function(resp) {
    console.log(resp)
})
```

![image](https://user-images.githubusercontent.com/1697158/64411602-21bf6380-d0c0-11e9-9790-7da6db0beb9c.png)
